$(document).ready(function(){
		$("#click1").click(function(){
			$("#1985").slideToggle("slow")
			$(".member").not("#1985").slideUp("slow");
			});
		$("#click2").click(function(){
			$("#1986").slideToggle("slow");
			$(".member").not("#1986").slideUp("slow");
			});
		$("#click3").click(function(){
			$("#1987").slideToggle("slow");
			$(".member").not("#1987").slideUp("slow");
			});
		$("#click4").click(function(){
			$("#1988").slideToggle("slow");
			$(".member").not("#1988").slideUp("slow");
			});
		$("#click5").click(function(){
			$("#1989").slideToggle("slow");
			$(".member").not("#1989").slideUp("slow");
			});
		$("#click6").click(function(){
			$("#1990").slideToggle("slow");
			$(".member").not("#1990").slideUp("slow");
			});
		$("#click7").click(function(){
			$("#1991").slideToggle("slow");
			$(".member").not("#1991").slideUp("slow");
			});
		$("#click8").click(function(){
			$("#1992").slideToggle("slow");
			$(".member").not("#1992").slideUp("slow");
			});
		$("#click9").click(function(){
			$("#1993").slideToggle("slow");
			$(".member").not("#1993").slideUp("slow");
			});
		$("#click10").click(function(){
			$("#1994").slideToggle("slow");
			$(".member").not("#1994").slideUp("slow");
			});
		$("#click11").click(function(){
			$("#1995").slideToggle("slow");
			$(".member").not("#1995").slideUp("slow");
			});
		$("#click12").click(function(){
			$("#1996").slideToggle("slow");
			$(".member").not("#1996").slideUp("slow");
			});
		$("#click13").click(function(){
			$("#1997").slideToggle("slow");
			$(".member").not("#1997").slideUp("slow");
			});
		$("#click14").click(function(){
			$("#1998").slideToggle("slow");
			$(".member").not("#1998").slideUp("slow");
			});
		$("#click15").click(function(){
			$("#1999").slideToggle("slow");
			$(".member").not("#1999").slideUp("slow");
			});
		$("#click16").click(function(){
			$("#2000").slideToggle("slow");
			$(".member").not("#2000").slideUp("slow");
			});
		$("#click17").click(function(){
			$("#2001").slideToggle("slow");
			$(".member").not("#2001").slideUp("slow");
			});
		$("#click18").click(function(){
			$("#2002").slideToggle("slow");
			$(".member").not("#2002").slideUp("slow");
			});
		$("#click19").click(function(){
			$("#2003").slideToggle("slow");
			$(".member").not("#2003").slideUp("slow");
			});
		$("#click20").click(function(){
			$("#2004").slideToggle("slow");
			$(".member").not("#2004").slideUp("slow");
			});
		$("#click21").click(function(){
			$("#2005").slideToggle("slow");
			$(".member").not("#2005").slideUp("slow");
			});
		$("#click22").click(function(){
			$("#2006").slideToggle("slow");
			$(".member").not("#2006").slideUp("slow");
			});
		$("#click23").click(function(){
			$("#2007").slideToggle("slow");
			$(".member").not("#2007").slideUp("slow");
			});
		$("#click24").click(function(){
			$("#2008").slideToggle("slow");
			$(".member").not("#2008").slideUp("slow");
			});
		$("#click25").click(function(){
			$("#2009").slideToggle("slow");
			$(".member").not("#2009").slideUp("slow");
			});
		$("#click26").click(function(){
			$("#2010").slideToggle("slow");
			$(".member").not("#2010").slideUp("slow");
			});
		$("#click27").click(function(){
			$("#2011").slideToggle("slow");
			$(".member").not("#2011").slideUp("slow");
			});
		$("#click28").click(function(){
			$("#2012").slideToggle("slow");
			$(".member").not("#2012").slideUp("slow");
			});
		$("#click29").click(function(){
			$("#2013").slideToggle("slow");
			$(".member").not("#2013").slideUp("slow");
			});
		$("#click30").click(function(){
			$("#2014").slideToggle("slow");
			$(".member").not("#2014").slideUp("slow");
			});
		});
	